import org.apache.tools.ant.filters.ReplaceTokens
import tool.generator.GenerateLibs
import tool.generator.api.task.GenerateApi

plugins {
    id 'java'
    id 'maven-publish'
    id 'signing'
}

sourceCompatibility = 17
targetCompatibility = 17

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.13.4")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.13.4")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

test {
    useJUnitPlatform()
}

compileJava {
    // By default we do not generate API, since we believe this should be done on purpose.
    if (System.getProperty('build.debug.generate.api.enable')) {
        dependsOn 'generateApi'
    }
}

sourceSets {
    main.java.srcDirs = ['src/generated/java']
    raw.java.srcDirs = ['src/main/java']
}

tasks.register('generateApi', GenerateApi)

tasks.register('generateLibs', GenerateLibs) {
    it.dependsOn assemble
}

tasks.register('generateJniSources') {
    dependsOn compileJava
    doLast {
        def jniDir = project.file('build/jni')
        jniDir.deleteDir()
        jniDir.mkdirs()
        new com.badlogic.gdx.jnigen.NativeCodeGenerator().generate(
            project.file('src/generated/java').path,
            project.file('build/classes/java/main').path,
            jniDir.path
        )
        project.copy {
            ['include/imgui', 'include/imnodes', 'include/imgui-node-editor', 'include/imguizmo', 'include/implot', 'include/imgui_club/imgui_memory_editor', 'include/imgui-knobs'].each {
                from(rootProject.file(it)) { include('*.h', '*.cpp', '*.inl') }
            }
            from(rootProject.file('imgui-binding/src/main/native'))
            into(jniDir)
            duplicatesStrategy = DuplicatesStrategy.INCLUDE
        }
        project.copy {
            from(rootProject.file('imgui-binding/src/main/native/imconfig.h'))
            into(jniDir)
        }
    }
}

apply from: "$rootDir/publish.gradle"
configurePublishing('imgui-java-binding', 'JNI based binding for Dear ImGui', project.version)

jar {
    manifest {
        attributes  'Automatic-Module-Name': 'imgui.binding'
    }
}

processResources {
    filesMatching('**/imgui-java.properties') {
        filter(ReplaceTokens, tokens: [
                'version': version
        ])
    }
}
