/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImFont */

#ifndef _Included_imgui_ImFont
#define _Included_imgui_ImFont
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImFont
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_moulberry90_ImFont_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nGetFallbackAdvanceX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nGetFallbackAdvanceX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetFallbackAdvanceX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetFallbackAdvanceX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nGetFontSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nGetFontSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetFontSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetFontSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nGetFallbackGlyph
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_moulberry90_ImFont_nGetFallbackGlyph
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetFallbackGlyph
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetFallbackGlyph
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImFont
 * Method:    nGetConfigDataCount
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_moulberry90_ImFont_nGetConfigDataCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetConfigDataCount
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetConfigDataCount
  (JNIEnv *, jobject, jshort);

/*
 * Class:     imgui_ImFont
 * Method:    nGetEllipsisChar
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_moulberry90_ImFont_nGetEllipsisChar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetEllipsisChar
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetEllipsisChar
  (JNIEnv *, jobject, jshort);

/*
 * Class:     imgui_ImFont
 * Method:    nGetEllipsisCharCount
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_moulberry90_ImFont_nGetEllipsisCharCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetEllipsisCharCount
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetEllipsisCharCount
  (JNIEnv *, jobject, jshort);

/*
 * Class:     imgui_ImFont
 * Method:    nGetEllipsisWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nGetEllipsisWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetEllipsisWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetEllipsisWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nGetEllipsisCharStep
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nGetEllipsisCharStep
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetEllipsisCharStep
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetEllipsisCharStep
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nGetDirtyLookupTables
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_moulberry90_ImFont_nGetDirtyLookupTables
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetDirtyLookupTables
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetDirtyLookupTables
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImFont
 * Method:    nGetScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nGetScale
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nGetAscent
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nGetAscent
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetAscent
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetAscent
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nGetDescent
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nGetDescent
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetDescent
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetDescent
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nGetMetricsTotalSurface
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_moulberry90_ImFont_nGetMetricsTotalSurface
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nSetMetricsTotalSurface
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nSetMetricsTotalSurface
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFont
 * Method:    nFindGlyph
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_moulberry90_ImFont_nFindGlyph
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFont
 * Method:    nFindGlyphNoFallback
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_moulberry90_ImFont_nFindGlyphNoFallback
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFont
 * Method:    nGetCharAdvance
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nGetCharAdvance
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFont
 * Method:    nIsLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_moulberry90_ImFont_nIsLoaded
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nGetDebugName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_moulberry90_ImFont_nGetDebugName
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeA
 * Signature: (Limgui/moulberry90/ImVec2;FFFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nCalcTextSizeA__Limgui_moulberry90_ImVec2_2FFFLjava_lang_String_2
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeAX
 * Signature: (FFFLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nCalcTextSizeAX__FFFLjava_lang_String_2
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeAY
 * Signature: (FFFLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nCalcTextSizeAY__FFFLjava_lang_String_2
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeA
 * Signature: (Limgui/moulberry90/ImVec2;FFFLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nCalcTextSizeA__Limgui_moulberry90_ImVec2_2FFFLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jstring, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeAX
 * Signature: (FFFLjava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nCalcTextSizeAX__FFFLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jstring, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcTextSizeAY
 * Signature: (FFFLjava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_moulberry90_ImFont_nCalcTextSizeAY__FFFLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jstring, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nCalcWordWrapPositionA
 * Signature: (FLjava/lang/String;Ljava/lang/String;F)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_moulberry90_ImFont_nCalcWordWrapPositionA
  (JNIEnv *, jobject, jfloat, jstring, jstring, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderChar
 * Signature: (JFFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nRenderChar
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderText
 * Signature: (JFFFIFFFFLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nRenderText__JFFFIFFFFLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jfloat, jfloat, jstring, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderText
 * Signature: (JFFFIFFFFLjava/lang/String;Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nRenderText__JFFFIFFFFLjava_lang_String_2Ljava_lang_String_2F
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jfloat, jfloat, jstring, jstring, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderText
 * Signature: (JFFFIFFFFLjava/lang/String;Ljava/lang/String;FZ)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nRenderText__JFFFIFFFFLjava_lang_String_2Ljava_lang_String_2FZ
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jfloat, jfloat, jstring, jstring, jfloat, jboolean);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderText
 * Signature: (JFFFIFFFFLjava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_imgui_moulberry90_ImFont_nRenderText__JFFFIFFFFLjava_lang_String_2Ljava_lang_String_2Z
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jfloat, jfloat, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
